### ISSUE TITLE
Fix ChatterPayNFT original / copyMint to proxy

### ISSUE THREAD

**Issue by TomasDmArg** [P4-Games/ChatterPay-SmartContracts#29]
- [x] Remove `setAuthorized`
- [x] Remove modifier `onlyOwnerOrAuthorized`
- [x] Switch `_safeMint` to `_mint` in order to not change proxies
- [x] Redeploy contract and verify

**Comment by dappsar** [comment]
Related to commit: https://github.com/P4-Games/ChatterPay-SmartContracts/commit/1d3f2964c686dce4cfc23308e3f2cff02ac859c8
